#!/usr/bin/env node
/**
 * Build WordPress/database/seed/* from the original MI TRENDS project.
 *
 *   node tools/build-seed.mjs
 *
 * Reads (never writes) ../mi-trends:
 *   lib/catalog.ts                 products, collections, categories
 *   lib/admin/data.ts              per-size stock, cost price, description, coupons
 *   app/(store)/info/[slug]/page.tsx  info page copy and FAQs
 * The TypeScript files are copied to a temp folder with their "@/..." imports
 * rewritten, then loaded with Node's built-in type stripping (Node 22.6+).
 *
 * Writes:
 *   database/seed/catalog.json           what the MI Trends Core importer loads
 *   database/seed/coupons.json
 *   database/seed/pages.json             info pages, wishlist, FAQs as block content
 *   database/seed/woocommerce-products.csv  same catalogue for WooCommerce's CSV importer
 */
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, "..");
const original = path.resolve(root, "..", "mi-trends");
const out = path.join(root, "database", "seed");
fs.mkdirSync(out, { recursive: true });

if (!fs.existsSync(original)) {
  console.error(`Original project not found at ${original}`);
  process.exit(1);
}

/* ---------- load the TypeScript sources from a temp copy ---------- */

const tmp = fs.mkdtempSync(path.join(os.tmpdir(), "mi-seed-"));
const catalogSrc = fs
  .readFileSync(path.join(original, "lib/catalog.ts"), "utf8")
  .replace('import type { Product, ProductColor } from "@/lib/types";', "type ProductColor = { name: string; hex: string }; type Product = any;");
fs.writeFileSync(path.join(tmp, "catalog.ts"), catalogSrc);

const dataSrc = fs
  .readFileSync(path.join(original, "lib/admin/data.ts"), "utf8")
  .replace('import { collections, products } from "@/lib/catalog";', 'import { collections, products } from "./catalog.ts";')
  .replace(/import type \{[^}]*\} from "@\/lib\/admin\/types";/s, "type ActivityItem=any;type AdminProduct=any;type Banner=any;type CategoryNode=any;type Coupon=any;type Customer=any;type Order=any;type OrderStatus=any;type PaymentMode=any;type Review=any;type SalesPoint=any;");
fs.writeFileSync(path.join(tmp, "data.ts"), dataSrc);

const catalog = await import(pathToFileURL(path.join(tmp, "catalog.ts")).href);
const admin = await import(pathToFileURL(path.join(tmp, "data.ts")).href);

const infoSrc = fs.readFileSync(path.join(original, "app/(store)/info/[slug]/page.tsx"), "utf8");
const grab = (start, end) => {
  const a = infoSrc.indexOf(start) + start.length;
  const b = infoSrc.indexOf(end, a);
  return infoSrc.slice(a, b + end.length - 1);
};
const simplePages = eval("(" + grab("const SIMPLE_PAGES: Record<string, PageContent> = ", "\n};") + ")");
const faqCategories = eval("(" + grab("const faqCategories = ", "\n];") + ")");

fs.rmSync(tmp, { recursive: true, force: true });

/* ---------- catalog.json ---------- */

const adminById = new Map(admin.adminProducts.map((p) => [p.id, p]));
const imageFile = (url) => (url ? path.basename(url) : null);

const products = catalog.products.map((p, index) => {
  const a = adminById.get(p.id);
  return {
    original_id: p.id,
    menu_order: index,
    slug: p.slug,
    name: p.name,
    sku: p.sku,
    description: a.description,
    category: p.category,
    collection: p.collectionSlug,
    type: p.type,
    tags: p.tags,
    colors: p.colors,
    sizes: p.sizes,
    stock: a.stock,
    mrp: p.mrp,
    price: p.price,
    cost_price: a.costPrice,
    rating: p.rating,
    review_count: p.reviewCount,
    popularity: p.popularity,
    featured: a.featured,
    fit: p.fit,
    fabric: p.fabric,
    art: p.art,
    palette: p.palette,
    image: imageFile(p.imageUrl),
    back_image: imageFile(p.backImageUrl),
    seo_title: a.seoTitle,
    seo_description: a.seoDescription,
  };
});

const catalogJson = {
  _source: "Generated by tools/build-seed.mjs from mi-trends/lib/catalog.ts and lib/admin/data.ts. Do not edit by hand; re-run the script.",
  sizes: ["XS", "S", "M", "L", "XL", "XXL"],
  categories: catalog.categories,
  collections: catalog.collections.map(({ name, slug, tagline, description, motif, palette }) => ({ name, slug, tagline, description, motif, palette })),
  types: [...new Set(catalog.products.map((p) => p.type))].map((name) => ({ name, slug: name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") })),
  tags: [
    { name: "New", slug: "new" },
    { name: "Bestseller", slug: "bestseller" },
    { name: "Sale", slug: "sale" },
  ],
  products,
};
fs.writeFileSync(path.join(out, "catalog.json"), JSON.stringify(catalogJson, null, 2) + "\n");

/* ---------- coupons.json ---------- */
// The three storefront codes (StoreProvider.tsx) are always valid there, so they
// import without an expiry. The panel-only demo codes keep their state.
const storefront = new Set(["MI10", "FLAT200", "FIRST15"]);
const coupons = admin.coupons.map((c) => {
  const base = {
    code: c.code,
    usage_limit: c.usageLimit,
    minimum_amount: c.minimumSpend,
    status: c.status,
    individual_use: true,
  };
  if (c.code === "FIRST15") {
    // 15% up to ₹400 (calculateCouponDiscount): fixed cart with "percent, capped".
    return { ...base, discount_type: "fixed_cart", amount: 400, capped_percent: 15, publish: true };
  }
  if (c.type === "percent") return { ...base, discount_type: "percent", amount: c.value, publish: c.status === "active" };
  if (c.type === "flat") return { ...base, discount_type: "fixed_cart", amount: c.value, publish: c.status === "active", expires: storefront.has(c.code) ? null : c.status === "expired" ? c.expiresAt.slice(0, 10) : null };
  return { ...base, discount_type: "fixed_cart", amount: 0, free_shipping: true, publish: c.status === "active" };
});
fs.writeFileSync(path.join(out, "coupons.json"), JSON.stringify({ _source: "Generated from mi-trends/lib/admin/data.ts (coupons) and StoreProvider.tsx rules.", coupons }, null, 2) + "\n");

/* ---------- pages.json ---------- */

const esc = (text) => String(text).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
const section = (heading, body) =>
  `<!-- wp:group {"className":"simple-section","layout":{"type":"constrained"}} -->\n<div class="wp-block-group simple-section">` +
  `<!-- wp:heading -->\n<h2 class="wp-block-heading">${esc(heading)}</h2>\n<!-- /wp:heading -->` +
  body.map((p) => `\n\n<!-- wp:paragraph -->\n<p>${esc(p)}</p>\n<!-- /wp:paragraph -->`).join("") +
  `</div>\n<!-- /wp:group -->`;

const faqContent = faqCategories
  .map(
    (cat) =>
      `<!-- wp:heading -->\n<h2 class="wp-block-heading">${esc(cat.heading)}</h2>\n<!-- /wp:heading -->\n\n` +
      cat.items
        .map((item) => `<!-- wp:details -->\n<details class="wp-block-details"><summary>${esc(item.q)}</summary><!-- wp:paragraph -->\n<p>${esc(item.a)}</p>\n<!-- /wp:paragraph --></details>\n<!-- /wp:details -->`)
        .join("\n\n"),
  )
  .join("\n\n");

const titles = {
  about: "Our story", careers: "Careers", press: "Press", "gift-cards": "Gift cards", stores: "Stores",
  shipping: "Shipping", returns: "Returns", terms: "Terms of service", privacy: "Privacy policy", accessibility: "Accessibility",
};

const info = Object.entries(simplePages).map(([slug, page]) => ({
  slug,
  title: titles[slug] || slug,
  template: slug === "gift-cards" || slug === "stores" ? "page-templates/info-notify.php" : "",
  eyebrow: page.eyebrow,
  display_title: page.title.replace(/\n/g, "|"),
  intro: page.intro,
  content: page.sections.map((s) => section(s.heading, s.body)).join("\n\n"),
}));

// Pages whose body is a template in the original (special in info/[slug]/page.tsx).
info.push(
  { slug: "contact", title: "Contact us", template: "page-templates/info-contact.php", eyebrow: "We're here", display_title: "TALK TO|A HUMAN.", intro: "Order questions, sizing help, or just feedback — send it over.", content: "" },
  { slug: "faqs", title: "FAQs", template: "page-templates/info-faqs.php", eyebrow: "Quick answers", display_title: "FREQUENTLY|ASKED.", intro: "Everything most people ask before or after ordering.", content: faqContent },
  { slug: "track-order", title: "Track order", template: "page-templates/info-track-order.php", eyebrow: "Where's my order", display_title: "TRACK YOUR|ORDER.", intro: "Enter your order ID to see the latest status.", content: "" },
  { slug: "size-guide", title: "Size guide", template: "page-templates/info-size-guide.php", eyebrow: "Find your fit", display_title: "SIZE|GUIDE.", intro: "Measurements are in inches unless noted, for the most reliable fit.", content: "" },
  { slug: "account", title: "Account help", template: "page-templates/info-account.php", eyebrow: "Your account", display_title: "YOUR MI TRENDS|ACCOUNT.", intro: "Sign in to shop — your bag, wishlist and order history live here.", content: "" },
);

const pages = {
  _source: "Generated from mi-trends/app/(store)/info/[slug]/page.tsx (SIMPLE_PAGES, faqCategories and the special pages).",
  pages: [
    { slug: "wishlist", title: "Wishlist", template: "page-templates/wishlist.php", content: "" },
    { slug: "info", title: "Info", template: "", eyebrow: "Help & info", display_title: "HELP &|INFO.", intro: "Shipping, returns, sizing and everything else.", content: "", children: info },
  ],
};
fs.writeFileSync(path.join(out, "pages.json"), JSON.stringify(pages, null, 2) + "\n");

/* ---------- woocommerce-products.csv ---------- */
// Optional route: WooCommerce → Products → Import. Replace {{IMAGE_BASE}} with the
// URL the photos are served from (see MIGRATION-GUIDE.md). The "MI …" columns are
// mapped by MI Trends Core's importer extension.
const cols = [
  "ID", "Type", "SKU", "Name", "Published", "Is featured?", "Visibility in catalog", "Short description", "Description",
  "In stock?", "Stock", "Sale price", "Regular price", "Categories", "Tags", "Images", "Parent", "Position",
  "Attribute 1 name", "Attribute 1 value(s)", "Attribute 1 visible", "Attribute 1 global",
  "MI Collection", "MI Type", "MI Colours", "MI Fit", "MI Fabric", "MI Artwork", "MI Palette", "MI Cost price", "MI Popularity", "MI Rating", "MI Review count",
];
const csvCell = (v) => {
  const s = v === null || v === undefined ? "" : String(v);
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
};
const rows = [cols];
for (const p of products) {
  const cat = catalog.categories.find((c) => c.slug === p.category)?.name ?? p.category;
  const images = [p.image, p.back_image].filter(Boolean).map((f) => `{{IMAGE_BASE}}/${f}`).join(", ");
  rows.push([
    "", "variable", p.sku, p.name, 1, p.featured ? 1 : 0, "visible", "", p.description,
    1, "", "", "", cat, p.tags.join(", "), images, "", p.menu_order,
    "Size", p.sizes.join(", "), 1, 1,
    p.collection, p.type, p.colors.map((c) => `${c.name} | ${c.hex}`).join("; "), p.fit, p.fabric, p.art, p.palette.join(" "), p.cost_price, p.popularity, p.rating, p.review_count,
  ]);
  p.sizes.forEach((size, i) => {
    const units = p.stock[size] ?? 0;
    rows.push([
      "", "variation", `${p.sku}-${size}`, `${p.name} - ${size}`, 1, "", "", "", "",
      units > 0 ? 1 : 0, units, p.price < p.mrp ? p.price : "", p.mrp, "", "", "", p.sku, i + 1,
      "Size", size, "", 1,
      "", "", "", "", "", "", "", "", "", "", "",
    ]);
  });
}
fs.writeFileSync(path.join(out, "woocommerce-products.csv"), rows.map((r) => r.map(csvCell).join(",")).join("\n") + "\n");

console.log(`Wrote ${products.length} products, ${coupons.length} coupons, ${info.length + 2} pages to ${out}`);
